blog/urls.py
from django.urls import path,re_path
from blog import views
app_name='blog'
urlpatterns = [
    path('',views.PostLV.as_view(),name='index'),
    path('post/',views.PostLV.as_view(),name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)/$',views.PostDV.as_view(),name='post_detail'),
    path('archive/',views.PostAV.as_view(),name='post_archive'),
    path('archive/<int:year>/',views.PostYAV.as_view(),name='post_year_archive'),
    path('archive/<int:year>/<str:month>/',views.PostMAV.as_view(),name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/',views.PostDAV.as_view(),name='post_day_archive'),
    path('archive/today/',views.PostTAV.as_view(),name='post_today_archive'),
    path('tag/',views.TagCloudTV.as_view(),name='tag_cloud'),
    path('tag/<str:tag>/',views.TaggedObjectLV.as_view(),name='tagged_object_list'),
    path('search/',views.SearchFormView.as_view(),name='search'),
    path('add/',views.PostCreateView.as_view(),name='add'),
    path('change/',views.PostChangeLV.as_view(),name='change'),
    path('<int:pk>/update/',views.PostUpdateView.as_view(),name='update'),
    path('<int:pk>/delete/',views.PostDeleteView.as_view(),name='delete'),
]

bookmark/urls.py
from django.urls import path
# from bookmark.views import BookmarkDV,BookmarkLV
from bookmark import views
app_name='bookmark'
urlpatterns = [
    path('', views.BookmarkLV.as_view(),name='index'),
    path('<int:pk>/', views.BookmarkDV.as_view(),name='detail'),
    path('add/',views.BookmarkCreateView.as_view(),name='add'),
    path('change/',views.BookmarkChangeLV.as_view(),name='change'),
    path('<int:pk>/update/',views.BookmarkUpdateView.as_view(),name='update'),
    path('<int:pk>/delete/',views.BookmarkDeleteView.as_view(),name='delete'),

    # path('')
    # path('/<int:pk>/')
]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from .views import HomeView,UserCreateView,UserCreateDoneTV
from django.conf.urls.static import static
from . import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(),name='home'),
    path('bookmark/',include('bookmark.urls')),
    path('blog/',include('blog.urls')),
    path('photo/',include('photo.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/register/',UserCreateView.as_view(),name='register'),
    path('accounts/register/done/',UserCreateDoneTV.as_view(),name='register_done'),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path,include
from . import views


app_name='photo'
urlpatterns = [
   path('',views.AlbumLV.as_view(),name='index'),
   path('album/',views.AlbumLV.as_view(),name='album_list'),
   path('album/<int:pk>/',views.AlbumDV.as_view(),name='album_detail'),
   path('photo/<int:pk>/',views.PhotoDV.as_view(),name='photo_detail'),
   path('album/add/',views.AlbumPhotoCV.as_view(),name='album_add'),
   path('album/change/',views.AlbumChangeLV.as_view(),name='album_change'),
   path('album/<int:pk>/update/',views.AlbumPhotoUV.as_view(),name='album_update'),
   path('album/<int:pk>/delete/',views.AlbumDelV.as_view(),name='album_delete'),
   path('photo/add/',views.PhotoCV.as_view(),name='photo_add'),
   path('photo/change/',views.PhotoChangeLV.as_view(),name='photo_change'),
   path('photo/<int:pk>/update/',views.PhotoUV.as_view(),name='photo_update'),
   path('photo/<int:pk>/delete/',views.PhotoDelV.as_view(),name='photo_delete'),

]

templates/base.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width", initial-scale="1">
        <title>{%block title%}Django Web Programming{%endblock%}</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" >
        {%block extra-style%}{%endblock%}
    </head>
    <body style="padding-top:90px;">
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">Django - Python Web Programming</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" >
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item btn-btn-primary">
                    <a class="nav-link active" href="{%url 'home'%}">Home</a>
                  </li>
                  <li class="nav-item btn-btn-primary">
                    <a class="nav-link" href="{%url 'bookmark:index'%}">Bookmark</a>
                  </li>
                  <li class="nav-item btn-btn-primary">
                    <a class="nav-link" href="{%url 'blog:index'%}">Blog</a>
                  </li>
                  <li class="nav-item btn-btn-primary">
                    <a class="nav-link" href="{%url 'photo:index'%}">Photo</a>
                  </li>
                  <!-- 게시글추가드롭다운 -->
                  <li class="nav-item dropdown mx-1">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" >
                      Add
                    </a>
                    <ul class="dropdown-menu" >
                      <li><a class="dropdown-item" href="{%url 'bookmark:add'%}">Bookmark</a></li>
                      <li><a class="dropdown-item" href="{%url 'blog:add'%}">Post</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{%url 'photo:album_add'%}">Album</a></li>
                      <li><a class="dropdown-item" href="{%url 'photo:photo_add'%}">Photo</a></li>
                    </ul>
                  </li>
                  <li class="nav-item dropdown mx-1">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" >
                      Change
                    </a>
                    <ul class="dropdown-menu" >
                      <li><a class="dropdown-item" href="{%url 'bookmark:change'%}">Bookmark</a></li>
                      <li><a class="dropdown-item" href="{%url 'blog:change'%}">Post</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="{%url 'photo:album_change'%}">Album</a></li>
                      <li><a class="dropdown-item" href="{%url 'photo:photo_change'%}">Photo</a></li>
                    </ul>
                  </li>

                  <!-- archive드롭다운 -->
                  <li class="nav-item dropdown mx-1">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" >
                      Util
                    </a>
                    <ul class="dropdown-menu" >
                      <li><a class="dropdown-item" href="{%url 'admin:index'%}">Admin</a></li>
                      <div class="dropdown-driver"></div>
                      <li><a class="dropdown-item" href="{%url 'blog:post_archive'%}">Archive</a></li>
                      <li><a class="dropdown-item" href="{%url 'blog:search'%}">Search</a></li>
                    </ul>
                  </li>
                </ul>
                <form class="d-flex" action="" method="post">{%csrf_token%}
                  <input class="form-control me-2" type="search" placeholder="global Search" name="search_word">
                  <!-- <button class="btn btn-outline-success" type="submit">Search</button> -->
                </form>
                <!-- 사용자관련드롭다운 -->
                <ul class="navbar-nav ml-5 mr-5">
                  <li class="nav-item dropdown mx-1 btn btn-primary btn-sm">
                    {%if user.is_active%}
                    <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown">
                      <i class="fas fa-user"></i>&ensp;{%firstof user.get_short_name user.get_username%}&ensp;</a>
                    <div class="dropdown-menu">
                      <a class="dropdown-item" href="{%url 'logout'%}">Logout</a>
                      <a class="dropdown-item" href="{%url 'password_change'%}">Change Password</a>
                    </div>
                    {%else%}
                    <a class="nav-link dropdown-toggle text-white" href="#" data-bs-toggle="dropdown">
                      <i class="fas fa-user"></i>&ensp;Anonymous&ensp;</a>
                      <div class="dropdown-menu">
                        <a class="dropdown-item" href="{%url 'login'%}">Login</a>
                        <a class="dropdown-item" href="{%url 'register'%}">Register</a>
                      </div>
                      {%endif%}
                  </li>
                </ul>
            </div>
            </div>
          </nav>
          <div class="container ">
            {%block content%}{%endblock%}
          </div>
          {%block footer%}{%endblock%}
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" ></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" ></script>
        <script src="https://kit.fontawesome.com/ee443cb98b.js"></script>
        {%block extra-script%}{%endblock%}
    </body>
    </html>
    

templates/home.html
{%extends 'base.html'%}

{%load static%}

{%block title%}home.html{%endblock%}

{%block extra-style%}
<style type="text/css">
    .home-image{
        background-image :url("{%static 'img/mainimg.jpg'%}");
        background-repeat: no-repeat;
        background-position: center;
        background-size: 100%;
        height: 500px;
        border-top: 10px solid #ccc;
        border-bottom: 10px solid #ccc;
        padding: 20px 0 0 20px;
    }
    .title{
        color: #c80;
        font-weight: bold;
    }
    .powered{
        position: relative;
        top: 77%;
        color: #cc0;
        font-style: italic;
    }
</style>
{%endblock%}

{%block content%}
<div class="home-image">
    <h2 class="title">Django - Python Web Programming</h2>
    <h4 class="powered"><i class="fas fa-arrow-circle-right"></i>powered by django and bootstrap</h4>
</div>
<hr style="margin: 10px 0;">

<div class="row text-center">
    <div class="col-sm-6">
        <h3>Bookmark App</h3>
        <p>Bookmark is a Uniform Resource Identifiter (URI)
            that is stored for later retrieval in any of various storage formats.
            You can store your own bookmark by Bookmark application.
            It's also possible to update or delete your bookmarks.
        </p>
    </div>
    <div class="col-sm-6">
        <h3>Blog App</h3>
        <p>This application makes it possible to log daily events or write your own interests
            such as hobbies, techniques, etc.
            A typical blog combines text, digital images, and links to other blog, web pages,
            and other media related to its topic.
        </p>
    </div>
</div>

{%endblock content%}

{%block footer%}
<footer class="fixed-bottom bg-info">
    <div class="text-white font-italic text-right mr-5">Copyright &copy; 2022
        DjangoBook by yum</div>
</footer>
{%endblock%}